### ISSUE TITLE
Improve support for passing AbortSignal

### ISSUE THREAD

**Issue by assaf** [neet/masto.js#773] opened 2022-12-25 20:28 UTC
Three things I think could improve working with signals.

1. I'm getting the following type error: `Type 'AbortSignal' is missing the following properties from type 'AbortSignal': reason, throwIfAbortedts`.

    While Masto uses `AbortSignal` types from `node-fetch`, my app uses `AbortSignal` type from `lib.dom` since the target is a browser (I also can't pass `Headers` due to the same type conflict).

    FWIW I found https://www.npmjs.com/package/undici to have better API compatibility with the browser compared to `node-fetch`.

2. Make it easier to set a signal for the session: `login({ url, accessToken, signal })`.

3. Make it easier to set a signal for a specific request.

    This is not a common use case, I don't think it's worth adding that option to every API request, but some way of cloning the client with a different signal + access token.

**Comment by neet** [comment] 2022-12-26 17:18
> 1

As you pointed out, Masto.js uses node-fetch as a type definition for fetch API. You would face a type error when you use Request or AbortSignal exported from a module other than node-fetch. Internally, however, if there exists a wanted object in global scope it automatically switches to that one, so I would recommend you cast the value you provided for time being.

You may wonder why we don’t use types provided by lib-dom. This is because I couldn’t find a way to use type definitions from `tslib` in a specific part of the module. Apparently, if I add `dom` to `compilerOptions.libs`, they require end users to specify `dom` even if they use Node.js. On top of that, even if I forgot to import a ponyfill they think `AbortSignal` or `fetch` are present in global so `tsc` passes which would lead to a bug.

Because of the reasons above, Masto.js is currently using type definitions from node-fetch. Undici is a great library that meets with the WHATWG spec more, but it doesn’t work on Node.js older than 16.8 so I had to give it up. In Node.js newer than 18, there’s fetch API in global so we use it by default. I'm planning to switch the types to Undici when Node.js 16 meets with its EOL.

> 2

We are offering an option [`defaultRequestInit`](https://github.com/neet/masto.js/blob/dd0d649067b6a2b6e60fbb0a96597c373a255b00/src/config.ts#L25). I've decided to use `fetch` and other `Request` related classes as a language-level feature and not try to abstract them too much. So Masto.js accepts `RequestInit` by design and I don't find any problem there. 

> 3

This is reasonable. I'd work on it along with #764 probably, or I can make `defautlRequestInit` accept function so they create signals every time.

**Comment by assaf** [comment] 2022-12-26 18:50
> I'd rather prefer adding a second argument that specifies a `RequestInit` to every method from repositories.

I thought that would be too complicated, but I'd rather have an options argument on each request. That's easier than dealing with `login`.

I don't think it should be `RequestInit` though. `RequestInit` includes too many things that I expect the Masto API to ignore — HTTP method, request body, content type, etc. I think it should be a subset of properties (headers, signal, what else?)


> In Node.js newer than 18, there’s fetch API in global so we use it by default.

Node 18 ships with `undici` (https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental).

> You may wonder why we don’t use types provided by lib-dom. 

Not really. I only use `lib-dom` in code that runs in the browser/edge servers, and `@types/node` in code that runs on Node. The problem with `node-fetch` is that it's incompatible with both.

> would recommend you cast the value you provided for time being.

Another option is for the Masto API to use W3C types and then cast those to `node-fetch` behind the scenes as an implementation detail.

**Comment by neet** [comment] 2022-12-26 20:22
> RequestInit includes too many things

I agree. Currently, I omit `body` and `method` from it.
https://github.com/neet/masto.js/blob/dd0d649067b6a2b6e60fbb0a96597c373a255b00/src/login.ts#L24

On the other hand, however, I want to make it like an escape hatch from this library since we cannot completely assert that there is nobody who wants to configure things like `mode`, `cache`, `redirect` etc. So I want to allow users to set any options from `RequestInit` other than `body` and `method` which will be overridden later.

> use W3C types and then cast those to node-fetch

This is what I originally wanted to do, but I couldn't find how to get spec-compatible types while not using `compilerOptions.lib: ["dom"]` and not affecting the globals. Do you have any idea to achieve this? I imagine something like this:

```ts
import { AbortController, RequestInit } from "lib.dom"; // W3C compact type definitions

export function login(options: { requestInit?: RequestInit }) {...}
```

**Comment by assaf** [comment] 2022-12-26 21:27
I figured duck-typing is sufficient: I don't need to know who created the signal, only whether it has the method I need to call.

My function wraps `fetch`: it creates a new signal, registers to any signal supplied by the caller, and then calls `fetch` with the new signal.

Likewise, it creates a new `headers` object, adds any headers provided by the caller, and then sets the headers for the specific call.

So the API has two very simple type definitions:

```
type AbortSignal = {
   addEventListener(type: 'abort', listener: (this: AbortSignal, ev: Event) => any, options?: unknown): void;
}

type HeaderInit = {
    entries(): IterableIterator<[string, string]>;
}

export function api(..., options: { signal?: AbortSignal; headers?: HeaderInit  }) {
  const controller = new AbortController();
  if (options?.signal)
    options.signal.addEventListener('abort', () => controller.abort());

  const headers = new Headers();
  if (options?.headers)
    for (const [name, value] of options.headers)
      headers.set(name, value);

  ...
}
```

> we cannot completely assert that there is nobody who wants to configure things like mode, cache, redirect, etc.

What happens when the user globally sets `redirect=manual` and then calls `status.create`? Does the `create` method knows it needs to manually fetch the resource in this case? Or does the API type signature change to return `Promise<void>`? Or does it blow up with an error?

Would you say the option to set `redirect` globally is well documented, has non-surprising behavior, and will not suddenly change in a future release?

**Comment by neet** [comment] 2022-12-26 22:36
Thank you for the example. I’ll give it a try.

> redirect=manual

I didn't know how `manual` works. Thank you for letting me know.  

Although if I could abstract the parameters and eliminate unexpected errors it’s ideal, I wouldn’t be able to keep maintain it if I pick acceptable pairs of option and value and define them as parameters for login. It requires me to keep track of 10+ additional parameters.

Instead, if I let the parameter a `RequestInit`, what I have to do is just merging objects. It reduces what I have to understand a lot while I still can provide the ability for customise the request. It may cause a surprising behaviour indeed, but if you understand how fetch works you can handle it sufficiently, so I don’t think it’s critical for now.

**Comment by assaf** [comment] 2022-12-27 00:13
In my experience, whenever we added the generic abstraction to cover all possible cases, we discovered we only had 1/2 clear use cases, and the generic abstraction didn't handle them too well.

I think the API would be easier to use if `masto.statuses.fetch(id, options)` supported just two options, with the most minimal type signature, so you can pass anything that can trigger an abort for the signal, and any key/value pair for the headers.

http://wiki.c2.com/?YouArentGonnaNeedIt

**Comment by neet** [comment] 2022-12-27 01:23
I'm not saying you're wrong. I determined that it was the comprehensive and the simplest way to cover use cases by the lowest maintenance cost because even if I restrict functionality by my decision I cannot handle one feature request after another! I hope you understand🙏

**Comment by assaf** [comment] 2023-01-12 02:35
I ended up using `fetch` directly and deserializing the output with Masto. I think for my use case it was better to have fewer abstractions. OK if you want to close this.

**Comment by neet** [comment] 2023-07-27 06:59
Closing in favour of #885

**Closed by neet** 2023-07-27 06:59 UTC
Labels: bug, enhancement
