### ISSUE TITLE
Actually a question: how to validate a login?

### ISSUE THREAD

**Issue by GerritKuilder** [neet/masto.js#854] opened 2023-02-15 18:11 UTC
Trying to understand the documentation but not very successful yet.

I can use the login metthod as per examples but how can I validate if the login was succesful>

Sofar the masto object does not give me a lot of information and I saw there is something with an Account but masto.v1.Account gives me undefined. 

Not sure what I am doing wrong here.
if there are places in the docs that explains the details, pointers would be appreciated too.

Kind Regards,

Gerit Kuilder

**Comment by neet** [comment] 2023-02-18 05:06
Duplicate of #855

**Closed by neet** 2023-02-18 05:06 UTC
