### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by greyivy** [neet/masto.js#341] opened 2020-12-26 00:02 UTC
Has anyone had any luck getting this to run on react-native?

More specifically, the dependence on native modules and a regular expression seems to be breaking things. I'm fairly new to react-native so I don't have additional details yet.

**Comment by neet** [comment] 2020-12-26 05:52
Happy holidays @greyivy, I tested Masto.js only on Node.js and browsers, but I would like to make it work on more devices 😄 Could you provide a specific error you've got and/or its reproduction?

**Comment by neet** [comment] 2021-03-02 00:56
Closing due to inactivity

**Comment by shamoons** [comment] 2022-11-11 15:29
<img width="340" alt="image" src="https://user-images.githubusercontent.com/1019677/201372235-0bdfd1e4-f7c1-4d25-b398-81f771498453.png">
Seems to not work on React Native

**Comment by shamoons** [comment] 2022-11-12 19:20
Thanks for looking @neet

**Comment by shamoons** [comment] 2022-11-15 14:43
Just wanted to see if we had any traction here?

**Comment by neet** [comment] 2022-11-15 15:09
Hi @shamoons , sorry for the lack of information

Although I'm unfamiliar with React Native so I cannot say anything specific, the error seems to be caused by Masto.js trying to import Node.js module `querystring` which is seemingly unavailable in React Native environment.

I'm not sure whether it might be the case, but I opened PR #680 to make it work without `querystring`. So would you verify that it resolves the error? You can try it out with the following command

```bash
yarn add masto@4.6.2-rc1
# or if you're using npm
npm install masto@4.6.2-rc1
```

**Comment by shamoons** [comment] 2022-11-15 16:49
@neet - getting a new issue:
```
Error: ENOENT: no such file or directory, open '/Users/shamoon/Sites/stampede/HttpAxiosImpl@http:/192.168.5.48:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
```

I assume `masto` is using `axios` somewhere?

**Comment by shamoons** [comment] 2022-11-17 02:54
```
node_modules/masto/dist/index.js: querystring could not be found within the project or in these directories:
  node_modules/masto/node_modules
  node_modules
   5 | var axios = require('axios');
   6 | var changeCase = require('change-case');
>  7 | var querystring = require('querystring');
     |                            ^
   8 | var EventEmitter = require('eventemitter3');
   9 | var WebSocket$1 = require('isomorphic-ws');
```

This is with `"masto": "4.4.1",`

**Comment by neet** [comment] 2022-11-17 03:10
@343max 's workaround is clever to opt out of Node.js dependency in the old version but still have no idea why getting problems with 4.6.2.

@shamoons To clarify, just using 4.4.1 will not solve the error because @343max 's snippet above is using internal modules to customise the `login()`.

Again, could you please show me a repository to reproduce the error you are getting? I have no experience in React Native so I can't figure out what actual issues here just by pasting error messages 🙏

**Comment by 343max** [comment] 2022-11-17 16:18
@neet I added PR #682 that will revert a change you introduced recently that broke React Native compatibility.

**Comment by aarononeal** [comment] 2022-11-21 23:03
@neet Can't determine why but out of the box in my Expo / React Native app I'm getting the `no such file or directory` error reported by `shamoons` and it is worked around using what `343max` suggested to avoid the Axios dependency. Is there a different way to switch to `fetch` without relying on internal dependencies?

**Comment by shamoons** [comment] 2022-11-22 21:27
I tried `4.6.1`, no dice

**Comment by shamoons** [comment] 2022-12-01 13:40
Anyone have any ideas?

**Comment by aarononeal** [comment] 2022-12-01 16:52
I got it working using what 343max proposed, though not ideal. What issue are you running into with that workaround?

**Comment by shamoons** [comment] 2022-12-02 14:58
@aarononeal - are using version 4.6.1?

**Comment by aarononeal** [comment] 2022-12-03 22:37
@shamoons 4.6.6

**Comment by neet** [comment] 2024-04-24 15:24
I'm closing this issue as it seems that it doesn't happen anymore. For anyone who faced a similar problem, feel free to create another issue but don't forget to provide [a minimal reproducible example](https://antfu.me/posts/why-reproductions-are-required).

**Closed by neet** 2024-04-24 15:24 UTC
Labels: bug
